project_id = "efdvolifacsnmiinifiq"

[functions.ai-match]
verify_jwt = true

[functions.parse-cv]
verify_jwt = true

[functions.chatbot]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.temp-login]
verify_jwt = false

[functions.ai-compose-email]
verify_jwt = true

[functions.send-candidate-email]
verify_jwt = true

[functions.send-renewal-reminders]
verify_jwt = false

[functions.process-scheduled-emails]
verify_jwt = false

[functions.track-email]
verify_jwt = false

[functions.send-email-smtp]
verify_jwt = true

[functions.test-smtp]
verify_jwt = true

[functions.send-event-invitation]
verify_jwt = true