-- Add new email templates for all admin communications
INSERT INTO public.email_templates (name, subject, html_content, variables, is_active)
VALUES 
  ('welcome', 'Welcome to RecruitifyCRM!', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">Welcome to RecruitifyCRM!</h1><p>Hi {{name}},</p><p>Thank you for joining RecruitifyCRM. Your account has been created successfully.</p><p>You can now start using our AI-powered recruitment platform to streamline your hiring process.</p><p>If you have any questions, please contact us at info@recruitifycrm.com</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["name"]', true),
  ('invoice', 'Your Invoice from RecruitifyCRM', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">Invoice #{{invoice_number}}</h1><p>Hi {{name}},</p><p>Please find your invoice attached. The amount due is {{amount}} {{currency}}.</p><p>Due Date: {{due_date}}</p><p>If you have any questions about this invoice, please contact us at info@recruitifycrm.com</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["name", "invoice_number", "amount", "currency", "due_date"]', true),
  ('thank_you', 'Thank You for Your Payment', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">Thank You!</h1><p>Hi {{name}},</p><p>We have received your payment of {{amount}} {{currency}}. Thank you for your continued trust in RecruitifyCRM.</p><p>If you have any questions, please contact us at info@recruitifycrm.com</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["name", "amount", "currency"]', true),
  ('forgot_password', 'Reset Your Password - RecruitifyCRM', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">Reset Your Password</h1><p>Hi {{name}},</p><p>We received a request to reset your password. Click the button below to create a new password:</p><p style="margin: 30px 0;"><a href="{{reset_link}}" style="background-color: #0052CC; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Reset Password</a></p><p>If you did not request this, please ignore this email or contact us at info@recruitifycrm.com</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["name", "reset_link"]', true),
  ('user_invite', 'You Have Been Invited to RecruitifyCRM', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">You Are Invited!</h1><p>Hi,</p><p>{{inviter_name}} has invited you to join their team on RecruitifyCRM as a {{role}}.</p><p style="margin: 30px 0;"><a href="{{invite_link}}" style="background-color: #0052CC; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Accept Invitation</a></p><p>This invitation will expire in 7 days.</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["inviter_name", "role", "invite_link"]', true),
  ('account_verification', 'Verify Your Email - RecruitifyCRM', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">Verify Your Email</h1><p>Hi {{name}},</p><p>Thank you for signing up for RecruitifyCRM. Please verify your email address by clicking the button below:</p><p style="margin: 30px 0;"><a href="{{verification_link}}" style="background-color: #0052CC; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Verify Email</a></p><p>If you did not create an account, please ignore this email.</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["name", "verification_link"]', true),
  ('subscription_expired', 'Your RecruitifyCRM Subscription Has Expired', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><h1 style="color: #0052CC;">Subscription Expired</h1><p>Hi {{name}},</p><p>Your RecruitifyCRM subscription has expired. To continue using all features, please renew your subscription.</p><p style="margin: 30px 0;"><a href="{{renewal_link}}" style="background-color: #0052CC; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Renew Now</a></p><p>If you have any questions, please contact us at info@recruitifycrm.com</p><p>Best regards,<br>The RecruitifyCRM Team</p></div>', '["name", "renewal_link"]', true)
ON CONFLICT DO NOTHING;

-- Update existing templates to use new branding
UPDATE public.email_templates
SET 
  html_content = REPLACE(REPLACE(html_content, 'Recruitsy', 'RecruitifyCRM'), 'recruitsy', 'recruitifycrm'),
  updated_at = now();